# -*- coding: utf-8 -*-
"""
Dados de treinamento anotados para o classificador de intenções.
Cada entrada é (texto_exemplo, intenção).

Para expandir o modelo, adicione mais exemplos e re-execute:
    python -m nlp_processor.training.train
"""

TRAIN_DATA: list[tuple[str, str]] = [

    # ---- buscar_queimadas ----
    # variações diretas
    ("Quais foram os focos de incêndio em Ribeirão Preto em 2024?", "buscar_queimadas"),
    ("Mostra os focos de queimada no estado de São Paulo", "buscar_queimadas"),
    ("Quantos focos de queimada foram registrados em 2023?", "buscar_queimadas"),
    ("Incêndios florestais em Campinas no último ano", "buscar_queimadas"),
    ("Mapa de focos de calor em São Paulo", "buscar_queimadas"),
    ("Quero ver as queimadas detectadas pelo satélite AQUA", "buscar_queimadas"),
    ("Focos de incêndio em Presidente Prudente", "buscar_queimadas"),
    ("Onde ocorreram queimadas em 2025?", "buscar_queimadas"),
    ("Queimadas registradas entre janeiro e março de 2024", "buscar_queimadas"),
    ("Histórico de incêndios em Sorocaba", "buscar_queimadas"),
    ("Focos de calor detectados pelo VIIRS", "buscar_queimadas"),
    ("Houve queimadas em Bauru recentemente?", "buscar_queimadas"),
    ("Incêndios em áreas rurais de São Paulo", "buscar_queimadas"),
    ("Quero ver os focos de queimada de 2024 em Marília", "buscar_queimadas"),
    ("Monitoramento de queimadas em São José do Rio Preto", "buscar_queimadas"),
    ("Focos de incêndio em 2022 no estado inteiro", "buscar_queimadas"),
    ("Queimadas em Araçatuba no mês de setembro", "buscar_queimadas"),
    ("Mapa dos incêndios florestais em 2025", "buscar_queimadas"),
    # paráfrases e variações sintáticas
    ("Tem registro de fogo em Franca?", "buscar_queimadas"),
    ("Quero saber onde pegou fogo em SP", "buscar_queimadas"),
    ("Incendios no interior paulista 2024", "buscar_queimadas"),
    ("Dados de foco de calor Campinas", "buscar_queimadas"),
    ("Ocorrencias de incendio florestal em 2025", "buscar_queimadas"),
    ("Satelite registrou fogo em SP", "buscar_queimadas"),
    ("Ver queimadas no mapa de sao paulo", "buscar_queimadas"),
    ("ultimos registros de incendio no estado", "buscar_queimadas"),
    ("historico foco calor ribeirao preto", "buscar_queimadas"),
    ("onde tem queimada agora em sp", "buscar_queimadas"),
    ("fogo em mata em piracicaba", "buscar_queimadas"),
    ("quantos incendios em 2023 sorocaba", "buscar_queimadas"),

    # ---- buscar_desmatamentos ----
    ("Quais áreas sofreram desmatamento em São Paulo?", "buscar_desmatamentos"),
    ("Alertas de desmatamento no estado em 2024", "buscar_desmatamentos"),
    ("Desmatamento detectado pelo DETER em Campinas", "buscar_desmatamentos"),
    ("Mostre os alertas do PRODES para 2023", "buscar_desmatamentos"),
    ("Onde ocorreram desmatamentos recentes?", "buscar_desmatamentos"),
    ("Áreas desmatadas no Vale do Ribeira", "buscar_desmatamentos"),
    ("Supressão vegetal registrada no interior paulista", "buscar_desmatamentos"),
    ("Desmatamento em 2025 em São Paulo", "buscar_desmatamentos"),
    ("Alertas de supressão de vegetação nativa", "buscar_desmatamentos"),
    ("Quero ver o mapa de desmatamento recente", "buscar_desmatamentos"),
    ("Qual foi a área desmatada em 2024?", "buscar_desmatamentos"),
    ("Desmatamentos detectados por satélite em Sorocaba", "buscar_desmatamentos"),
    ("DETER alertas janeiro 2025", "buscar_desmatamentos"),
    ("Vegetação suprimida no último trimestre", "buscar_desmatamentos"),
    ("Histórico de desmatamento em Ribeirão Preto", "buscar_desmatamentos"),
    ("Alertas PRODES 2024 para o estado de SP", "buscar_desmatamentos"),
    # paráfrases
    ("Corte ilegal de arvores em SP", "buscar_desmatamentos"),
    ("Supressao de vegetacao nativa em 2024", "buscar_desmatamentos"),
    ("mapa de areas desmatadas paulista", "buscar_desmatamentos"),
    ("degradacao florestal no interior de sp", "buscar_desmatamentos"),
    ("alertas corte raso satelite sp", "buscar_desmatamentos"),
    ("onde foi removida vegetacao nativa", "buscar_desmatamentos"),
    ("levantamento desmatamento state sp 2023", "buscar_desmatamentos"),
    ("areas com supressao vegetal recente campinas", "buscar_desmatamentos"),
    ("desmatamento registrado no litoral paulista", "buscar_desmatamentos"),
    ("quanta mata foi derrubada em sp", "buscar_desmatamentos"),
    ("historico deter prodes sao paulo", "buscar_desmatamentos"),

    # ---- buscar_unidades_conservacao ----
    ("Quais são as unidades de conservação em São Paulo?", "buscar_unidades_conservacao"),
    ("Parques nacionais e estaduais do estado", "buscar_unidades_conservacao"),
    ("Mostre as APAs no estado de São Paulo", "buscar_unidades_conservacao"),
    ("Áreas protegidas no litoral paulista", "buscar_unidades_conservacao"),
    ("Quais parques existem em Campinas?", "buscar_unidades_conservacao"),
    ("Reservas biológicas de São Paulo", "buscar_unidades_conservacao"),
    ("RESEX no estado de São Paulo", "buscar_unidades_conservacao"),
    ("Unidades de proteção integral em SP", "buscar_unidades_conservacao"),
    ("Mapa das UCs de uso sustentável", "buscar_unidades_conservacao"),
    ("Parque Estadual da Serra do Mar", "buscar_unidades_conservacao"),
    ("Quais APAs existem no Vale do Paraíba?", "buscar_unidades_conservacao"),
    ("Estações ecológicas em São Paulo", "buscar_unidades_conservacao"),
    ("Floresta nacional em SP", "buscar_unidades_conservacao"),
    ("Mostre as RPPNs cadastradas no estado", "buscar_unidades_conservacao"),
    ("Parques municipais em São Paulo capital", "buscar_unidades_conservacao"),
    ("Quais UCs existem em Ubatuba?", "buscar_unidades_conservacao"),
    # paráfrases
    ("areas de protecao ambiental sp", "buscar_unidades_conservacao"),
    ("reservas naturais no estado de sao paulo", "buscar_unidades_conservacao"),
    ("ver parques e reservas em sc", "buscar_unidades_conservacao"),
    ("quero saber das ucs na regiao de campinas", "buscar_unidades_conservacao"),
    ("onde existem areas protegidas federais sp", "buscar_unidades_conservacao"),
    ("uc federal estadual sao paulo mapa", "buscar_unidades_conservacao"),
    ("mostre parque nacional sp", "buscar_unidades_conservacao"),
    ("reserva biologica federal SP", "buscar_unidades_conservacao"),
    ("zonas de protecao ambiental no estado", "buscar_unidades_conservacao"),
    ("quais sao as apa de sao paulo", "buscar_unidades_conservacao"),
    ("flona sp floresta nacional paulista", "buscar_unidades_conservacao"),

    # ---- buscar_terras_indigenas ----
    ("Quais são as terras indígenas em São Paulo?", "buscar_terras_indigenas"),
    ("Onde ficam os territórios indígenas no estado?", "buscar_terras_indigenas"),
    ("Terras indígenas homologadas em SP", "buscar_terras_indigenas"),
    ("Mapa das aldeias indígenas de São Paulo", "buscar_terras_indigenas"),
    ("TIs delimitadas no estado de São Paulo", "buscar_terras_indigenas"),
    ("Quais terras indígenas existem em Registro?", "buscar_terras_indigenas"),
    ("Indígenas Guarani no litoral sul paulista", "buscar_terras_indigenas"),
    ("Terras indígenas da FUNAI em SP", "buscar_terras_indigenas"),
    ("Demarcações indígenas ativas no estado", "buscar_terras_indigenas"),
    ("Quais TIs estão em fase de estudo em SP?", "buscar_terras_indigenas"),
    ("Territórios indígenas Krenak em SP", "buscar_terras_indigenas"),
    ("Áreas de habitação indígena no Vale do Ribeira", "buscar_terras_indigenas"),
    ("FUNAI demarcações São Paulo", "buscar_terras_indigenas"),
    # paráfrases
    ("aldeias indigenas no estado", "buscar_terras_indigenas"),
    ("populacoes indigenas em sp demarcacao", "buscar_terras_indigenas"),
    ("territorio guarani sao paulo", "buscar_terras_indigenas"),
    ("demarcacoes funai sp homologadas", "buscar_terras_indigenas"),
    ("area indigena no litoral", "buscar_terras_indigenas"),
    ("ti em fase de declaracao sao paulo", "buscar_terras_indigenas"),
    ("quais os povos indigenas em sp", "buscar_terras_indigenas"),
    ("reserva indigena sao paulo mapa", "buscar_terras_indigenas"),
    ("onde moram os indigenas em sao paulo", "buscar_terras_indigenas"),
    ("ti delimitada sao paulo", "buscar_terras_indigenas"),

    # ---- buscar_assentamentos ----
    ("Onde ficam os assentamentos rurais do INCRA em SP?", "buscar_assentamentos"),
    ("Assentamentos da reforma agrária no estado", "buscar_assentamentos"),
    ("Mostre os projetos de assentamento em Araçatuba", "buscar_assentamentos"),
    ("Assentamentos do MST em São Paulo", "buscar_assentamentos"),
    ("Quais assentamentos existem no Pontal do Paranapanema?", "buscar_assentamentos"),
    ("Famílias assentadas no interior paulista", "buscar_assentamentos"),
    ("Projetos de assentamento INCRA SP", "buscar_assentamentos"),
    ("Assentamentos rurais federais em SP", "buscar_assentamentos"),
    ("Áreas de assentamento no estado de São Paulo", "buscar_assentamentos"),
    ("Reforma agrária em Presidente Prudente", "buscar_assentamentos"),
    ("Assentamentos em Andradina e região", "buscar_assentamentos"),
    ("Mapa dos assentamentos em SP", "buscar_assentamentos"),
    # paráfrases
    ("lotes de reforma agraria em sp", "buscar_assentamentos"),
    ("projetos pa incra sao paulo", "buscar_assentamentos"),
    ("assentados no pontal do paranapanema", "buscar_assentamentos"),
    ("quantos assentamentos existem em sp", "buscar_assentamentos"),
    ("assentamento rural mapa interior paulista", "buscar_assentamentos"),
    ("reforma agraria campinas incra", "buscar_assentamentos"),
    ("onde tem assentamento no estado", "buscar_assentamentos"),
    ("familias beneficiadas reforma agraria sp", "buscar_assentamentos"),
    ("colonias e assentamentos no estado", "buscar_assentamentos"),
    ("ver projetos assentamento pe pa sao paulo", "buscar_assentamentos"),

    # ---- buscar_quilombolas ----
    ("Quais são os territórios quilombolas em SP?", "buscar_quilombolas"),
    ("Comunidades quilombolas no estado de São Paulo", "buscar_quilombolas"),
    ("Territórios quilombolas no Vale do Ribeira", "buscar_quilombolas"),
    ("Quilombos certificados em São Paulo", "buscar_quilombolas"),
    ("Palmares comunidades quilombolas SP", "buscar_quilombolas"),
    ("Terras de quilombo no litoral paulista", "buscar_quilombolas"),
    ("Mostre os quilombos em Eldorado", "buscar_quilombolas"),
    ("Territórios quilombolas titulados em SP", "buscar_quilombolas"),
    ("Quilombolas INCRA São Paulo", "buscar_quilombolas"),
    ("Comunidades remanescentes de quilombo no Vale do Ribeira", "buscar_quilombolas"),
    ("Onde ficam os territórios de quilombo no estado?", "buscar_quilombolas"),
    # paráfrases
    ("comunidades remanescentes quilombo sp", "buscar_quilombolas"),
    ("titulacao quilombola vale do ribeira", "buscar_quilombolas"),
    ("mapa quilombos sao paulo", "buscar_quilombolas"),
    ("areas quilombolas certifcadas palmares", "buscar_quilombolas"),
    ("quilombo em iguape e eldorado", "buscar_quilombolas"),
    ("territorio de quilombo litoral sul paulista", "buscar_quilombolas"),
    ("onde ficam os quilombolas em sp", "buscar_quilombolas"),
    ("quilombos rurais no estado de sao paulo", "buscar_quilombolas"),
    ("communidades tradicionais quilombolas sp", "buscar_quilombolas"),

    # ---- buscar_imoveis_rurais ----
    ("Imóveis rurais cadastrados no CAR em Campinas", "buscar_imoveis_rurais"),
    ("Quero ver os imóveis do Cadastro Ambiental Rural", "buscar_imoveis_rurais"),
    ("CAR de propriedades rurais em São Paulo", "buscar_imoveis_rurais"),
    ("Propriedades rurais no estado", "buscar_imoveis_rurais"),
    ("Onde estão os imóveis rurais em Ribeirão Preto?", "buscar_imoveis_rurais"),
    ("Situação cadastral dos imóveis rurais em SP", "buscar_imoveis_rurais"),
    ("Imóveis com CAR ativo em Sorocaba", "buscar_imoveis_rurais"),
    ("Fazendas e sítios cadastrados no sistema", "buscar_imoveis_rurais"),
    ("Propriedades rurais com regularidade ambiental", "buscar_imoveis_rurais"),
    ("SICAR imóveis São Paulo", "buscar_imoveis_rurais"),
    ("Pequenas propriedades rurais no interior paulista", "buscar_imoveis_rurais"),
    # paráfrases
    ("fazenda com car sao paulo", "buscar_imoveis_rurais"),
    ("sitio registrado no car sp", "buscar_imoveis_rurais"),
    ("imovel rural regular em campinas", "buscar_imoveis_rurais"),
    ("cadastro ambiental rural ribeirao preto", "buscar_imoveis_rurais"),
    ("quantas propriedades tem car ativo em sp", "buscar_imoveis_rurais"),
    ("ver mapa sicar sao paulo", "buscar_imoveis_rurais"),
    ("imovel rural pendente no car", "buscar_imoveis_rurais"),
    ("quero o codigo car de propriedade rural", "buscar_imoveis_rurais"),
    ("qual a situacao do car na minha regiao", "buscar_imoveis_rurais"),
    ("levantamento propriedades rurais estado", "buscar_imoveis_rurais"),

    # ---- buscar_camadas_estaduais ----
    ("Quais são as camadas ambientais estaduais em São Paulo?", "buscar_camadas_estaduais"),
    ("Mostre as camadas ambientais no estado", "buscar_camadas_estaduais"),
    ("Onde ficam as áreas de proteção ambiental estaduais?", "buscar_camadas_estaduais"),
    ("Camadas estaduais ambientais em Campinas", "buscar_camadas_estaduais"),
    ("Quais são as unidades de proteção integral do estado?", "buscar_camadas_estaduais"),
    ("Áreas de uso sustentável estadual em SP", "buscar_camadas_estaduais"),
    ("Mapa das camadas ambientais do estado de São Paulo", "buscar_camadas_estaduais"),
    ("Quais são as áreas ambientais estaduais em Ribeirão Preto?", "buscar_camadas_estaduais"),
    ("Camadas ambientais do DataGeo SP", "buscar_camadas_estaduais"),
    ("Zonas de proteção ambiental estadual", "buscar_camadas_estaduais"),
    ("Áreas ambientais estaduais em Sorocaba", "buscar_camadas_estaduais"),
    ("Quais camadas ambientais existem no litoral paulista?", "buscar_camadas_estaduais"),
    ("Mapa de proteção ambiental estadual do estado", "buscar_camadas_estaduais"),
    ("Temas de proteção ambiental estado de São Paulo", "buscar_camadas_estaduais"),
    # paráfrases
    ("camadas estaduais de protecao ambiental", "buscar_camadas_estaduais"),
    ("areas ambientais estaduais sao paulo", "buscar_camadas_estaduais"),
    ("zonas de protecao ambiental estado", "buscar_camadas_estaduais"),
    ("quais sao as camadas ambientais de sp", "buscar_camadas_estaduais"),
    ("datageo sp camadas ambientais estado", "buscar_camadas_estaduais"),
    ("areas de uso sustentavel estadual", "buscar_camadas_estaduais"),
    ("protecao ambiental estadual no estado de sao paulo", "buscar_camadas_estaduais"),
    ("mapa camadas ambientais estaduais", "buscar_camadas_estaduais"),
    ("quais as zonas ambientais estaduais em ribeirao", "buscar_camadas_estaduais"),

    # ---- buscar_imoveis_em_camadas ----
    ("Quais propriedades rurais estão em camadas ambientais?", "buscar_imoveis_em_camadas"),
    ("Propriedades rurais em áreas de proteção ambiental estadual", "buscar_imoveis_em_camadas"),
    ("Imóveis rurais dentro de camadas ambientais estaduais", "buscar_imoveis_em_camadas"),
    ("Mostre as fazendas em áreas ambientais do estado", "buscar_imoveis_em_camadas"),
    ("Propriedades que intersectam camadas estaduais ambientais", "buscar_imoveis_em_camadas"),
    ("Quais propriedades rurais estão em zonas de proteção ambiental?", "buscar_imoveis_em_camadas"),
    ("Imóveis com CAR em camadas ambientais estaduais", "buscar_imoveis_em_camadas"),
    ("Propriedades rurais em zonas ambientais do estado", "buscar_imoveis_em_camadas"),
    ("Sobreposição de propriedades rurais com camadas ambientais", "buscar_imoveis_em_camadas"),
    ("Qual a situação de propriedades em áreas ambientais estaduais?", "buscar_imoveis_em_camadas"),
    ("Propriedades rurais em Campinas que estão em camadas ambientais", "buscar_imoveis_em_camadas"),
    ("Mapa de imóveis rurais em areas de proteção estadual", "buscar_imoveis_em_camadas"),
    ("Qual a área de propriedades rurais em camadas ambientais?", "buscar_imoveis_em_camadas"),
    ("Propriedades sobrepostas a áreas ambientais estaduais", "buscar_imoveis_em_camadas"),
    # paráfrases
    ("propriedades rurais em protecao ambiental estadual", "buscar_imoveis_em_camadas"),
    ("imoveis rurais em camadas ambientais estado", "buscar_imoveis_em_camadas"),
    ("quais propriedades rurais estao em zonas ambientais", "buscar_imoveis_em_camadas"),
    ("fazendas em areas de protecao ambiental estadual", "buscar_imoveis_em_camadas"),
    ("car propriedades em camadas ambientais estaduais", "buscar_imoveis_em_camadas"),
    ("sobreposicao entre imoveis rurais e camadas ambientais", "buscar_imoveis_em_camadas"),
    ("propriedades rurais intersectando camadas ambientais", "buscar_imoveis_em_camadas"),
    ("area de imoveis rurais em zonas ambientais", "buscar_imoveis_em_camadas"),
    ("mapa propriedades rurais zonas protecao ambiental estado", "buscar_imoveis_em_camadas"),
    ("quais sao as propriedades em camadas ambientais estaduais", "buscar_imoveis_em_camadas"),

    # ---- buscar_documentos ----

    # ---- buscar_passivos_imovel ----
    ("Quais passivos ambientais existem na propriedade SP000123456?", "buscar_passivos_imovel"),
    ("Quais passivos ambientais estão presentes na propriedade com código CAR SP000123456?", "buscar_passivos_imovel"),
    ("Que passivos ambientais existem dentro do imóvel SP000123456?", "buscar_passivos_imovel"),
    ("Mostrar queimadas e desmatamentos dentro da propriedade SP000123456", "buscar_passivos_imovel"),
    ("Quais passivos ambientais estão na fazenda com CAR SP000123456?", "buscar_passivos_imovel"),
    ("Passivos ambientais da propriedade SP000123456", "buscar_passivos_imovel"),
    ("Existe queimada ou desmatamento dentro do imóvel SP000123456?", "buscar_passivos_imovel"),
    ("Ver passivos ambientais por CAR SP000123456", "buscar_passivos_imovel"),
    ("Quais passivos ambientais estão sobrepostos ao imóvel SP000123456?", "buscar_passivos_imovel"),
    ("O que é o Código Florestal?", "buscar_documentos"),
    ("Qual a legislação sobre Reserva Legal em SP?", "buscar_documentos"),
    ("Explique o que é uma Unidade de Conservação", "buscar_documentos"),
    ("O que diz a lei sobre APPs?", "buscar_documentos"),
    ("Quais as regras do CAR?", "buscar_documentos"),
    ("Legislação ambiental de São Paulo", "buscar_documentos"),
    ("Como funciona o licenciamento ambiental em SP?", "buscar_documentos"),
    ("O que é o SNUC?", "buscar_documentos"),
    ("Explique o que é o PRODES", "buscar_documentos"),
    ("O que são Áreas de Preservação Permanente?", "buscar_documentos"),
    ("Quais as obrigações do CAR para pequenas propriedades?", "buscar_documentos"),
    ("Como é feito o monitoramento de queimadas no Brasil?", "buscar_documentos"),
    ("Qual a diferença entre DETER e PRODES?", "buscar_documentos"),
    ("Explique o Programa de Regularização Ambiental", "buscar_documentos"),
    # paráfrases
    ("o que diz o codigo florestal sobre reserva legal", "buscar_documentos"),
    ("lei de protecao ambiental sao paulo", "buscar_documentos"),
    ("o que e app area preservacao permanente", "buscar_documentos"),
    ("como regularizar imovel no car", "buscar_documentos"),
    ("o que significa snuc", "buscar_documentos"),
    ("como funciona o pra programa regularizacao ambiental", "buscar_documentos"),
    ("exlicacao sobre deter monitoramento", "buscar_documentos"),
    ("manual do car cadastro ambiental rural", "buscar_documentos"),
    ("legislacao sobre queimadas controladas", "buscar_documentos"),
    ("o que e reserva legal percentual", "buscar_documentos"),
    ("diferenca entre uc de uso sustentavel e protecao integral", "buscar_documentos"),
    ("lei 12651 codigo florestal brasileiro", "buscar_documentos"),

    # ---- fora_escopo ----
    ("Qual a previsão do tempo para amanhã?", "fora_escopo"),
    ("Me diga o PIB do estado de São Paulo", "fora_escopo"),
    ("Como fazer uma receita de bolo?", "fora_escopo"),
    ("Qual o resultado do jogo do Corinthians?", "fora_escopo"),
    ("Dados de desmatamento na Amazônia em 2024", "fora_escopo"),
    ("Queimadas no Pantanal mato-grossense", "fora_escopo"),
    ("Qual o preço do boi gordo hoje?", "fora_escopo"),
    ("Me fale sobre a história do Brasil", "fora_escopo"),
    ("Dados ambientais do estado do Paraná", "fora_escopo"),
    ("Terras indígenas no Pará", "fora_escopo"),
    ("Como está a seca no Nordeste?", "fora_escopo"),
    ("Dados climáticos do Rio de Janeiro", "fora_escopo"),
    ("Qual o partido político mais votado em SP?", "fora_escopo"),
    ("Cotação do dólar hoje", "fora_escopo"),
    ("Unidades de conservação no Amazonas", "fora_escopo"),
    # mais negativos (confusão potencial com escopo ambiental de outros estados)
    ("queimadas no cerrado goias", "fora_escopo"),
    ("desmatamento amazonia para 2024", "fora_escopo"),
    ("terras indigenas mato grosso", "fora_escopo"),
    ("assentamentos incra minas gerais", "fora_escopo"),
    ("unidades conservacao rio de janeiro", "fora_escopo"),
    ("previsao chuva campinas semana", "fora_escopo"),
    ("preco soja commodities hoje", "fora_escopo"),
    ("eleicoes municipais sp resultado", "fora_escopo"),
    ("temperatura media ribeirao preto", "fora_escopo"),
    ("dados demograficos sao paulo ibge", "fora_escopo"),
    ("queda energia eletrica campinas", "fora_escopo"),
    ("transito sao paulo capital agora", "fora_escopo"),
    ("quilombolas em pernambuco", "fora_escopo"),
    ("parques nacionais do sul do brasil", "fora_escopo"),
    ("reserva biologica espirito santo", "fora_escopo"),
]
