"""add_queimada_bioma_risco_columns

Revision ID: 632dddf75ddc
Revises: c301f9ab1d23
Create Date: 2026-04-01 22:03:35.488272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
import pgvector


# revision identifiers, used by Alembic.
revision: str = '632dddf75ddc'
down_revision: Union[str, Sequence[str], None] = 'c301f9ab1d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queimada_evento', sa.Column('bioma', sa.TEXT(), nullable=True))
    op.add_column('queimada_evento', sa.Column('dias_sem_chuva', sa.Integer(), nullable=True))
    op.add_column('queimada_evento', sa.Column('precipitacao_mm', sa.Numeric(), nullable=True))
    op.add_column('queimada_evento', sa.Column('risco_fogo', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queimada_evento', 'risco_fogo')
    op.drop_column('queimada_evento', 'precipitacao_mm')
    op.drop_column('queimada_evento', 'dias_sem_chuva')
    op.drop_column('queimada_evento', 'bioma')
    # ### end Alembic commands ###