"""empty message

Revision ID: 9a49363b9f8a
Revises: 
Create Date: 2026-03-27 10:37:52.257860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a49363b9f8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacia_hidrografica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('codigo', sa.TEXT(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conceito',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome_canonico', sa.TEXT(), nullable=True),
    sa.Column('tipo_conceito', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=2), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_espacial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('codigo', sa.TEXT(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intencao_consulta',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conceito_alias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('coceito_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['coceito_id'], ['conceito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta_usuario',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pergunta', sa.TEXT(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('intencao_detectada', sa.TEXT(), nullable=True),
    sa.Column('entidades_detectadas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filtros_detectados_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('intencao_id', sa.UUID(), nullable=True),
    sa.Column('intencao_score', sa.Numeric(), nullable=True),
    sa.Column('turno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['intencao_id'], ['intencao_consulta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'turno', name='idx_consulta_chat_turno')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_ibge', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assentamento_rural',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('modalidade', sa.TEXT(), nullable=True),
    sa.Column('familias', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camada_estadual_ambiental',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('subtipo', sa.TEXT(), nullable=True),
    sa.Column('tema', sa.TEXT(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desmatamento_alerta',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('data_ocorrencia', sa.Date(), nullable=True),
    sa.Column('tipo_alerta', sa.TEXT(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.TEXT(), nullable=True),
    sa.Column('tipo', sa.TEXT(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('texto_integral', sa.TEXT(), nullable=True),
    sa.Column('url_origem', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imovel_rural',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('nome_imovel', sa.TEXT(), nullable=True),
    sa.Column('codigo_car', sa.TEXT(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('situacao_cadastral', sa.TEXT(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queimada_evento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=True),
    sa.Column('fonte_sensor', sa.TEXT(), nullable=True),
    sa.Column('intensidade', sa.Numeric(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta_sistema',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consulta_usuario_id', sa.UUID(), nullable=False),
    sa.Column('texto_resposta', sa.TEXT(), nullable=True),
    sa.Column('sql_executado', sa.TEXT(), nullable=True),
    sa.Column('fontes_utilizadas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bbox_resultado', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tempo_resposta_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='sucesso', nullable=False),
    sa.Column('mensagem_erro', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('sucesso', 'erro', 'fallback', 'sem_resultado')", name='check_status_resposta'),
    sa.ForeignKeyConstraint(['consulta_usuario_id'], ['consulta_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terra_indigena',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('fase', sa.TEXT(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('territorio_quilombola',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_conservacao',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_origem', sa.TEXT(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('categoria', sa.TEXT(), nullable=True),
    sa.Column('esfera', sa.TEXT(), nullable=True),
    sa.Column('grupo_snuc', sa.TEXT(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('atributos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_trecho',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('tokens_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_resposta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resposta_sistema_id', sa.UUID(), nullable=False),
    sa.Column('avaliacao', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avaliacao IN (-1, 0, 1)', name='check_avaliacao_valor'),
    sa.ForeignKeyConstraint(['resposta_sistema_id'], ['resposta_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_resposta_resposta_sistema_id'), 'feedback_resposta', ['resposta_sistema_id'], unique=False)
    op.create_table('rel_imovel_assentamento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=True),
    sa.Column('assentamento_rural_id', sa.UUID(), nullable=True),
    sa.Column('area_intersecao_ha', sa.Numeric(), nullable=True),
    sa.Column('percentual_sobreposicao', sa.Numeric(), nullable=True),
    sa.Column('tipo_relacao', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['assentamento_rural_id'], ['assentamento_rural.id'], ),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_imovel_bacia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=False),
    sa.Column('bacia_hidrografica_id', sa.Integer(), nullable=False),
    sa.Column('area_intersecao_ha', sa.Numeric(), nullable=True),
    sa.Column('percentual_sobreposicao', sa.Numeric(), nullable=True),
    sa.Column('tipo_relacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bacia_hidrografica_id'], ['bacia_hidrografica.id'], ),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_imovel_desmatamento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=True),
    sa.Column('desmatamento_alerta_id', sa.UUID(), nullable=True),
    sa.Column('area_intersecao_ha', sa.Numeric(), nullable=True),
    sa.Column('percentual_sobreposicao', sa.Numeric(), nullable=True),
    sa.Column('data_calculo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['desmatamento_alerta_id'], ['desmatamento_alerta.id'], ),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_imovel_queimada',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=True),
    sa.Column('queimada_evento_id', sa.UUID(), nullable=True),
    sa.Column('distancia_m', sa.Numeric(), nullable=True),
    sa.Column('dentro_imovel', sa.Boolean(), nullable=True),
    sa.Column('data_calculo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.ForeignKeyConstraint(['queimada_evento_id'], ['queimada_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_imovel_quilombo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=True),
    sa.Column('territorio_quilombola_id', sa.UUID(), nullable=True),
    sa.Column('area_intersecao_ha', sa.Numeric(), nullable=True),
    sa.Column('percentual_sobreposicao', sa.Numeric(), nullable=True),
    sa.Column('tipo_relacao', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.ForeignKeyConstraint(['territorio_quilombola_id'], ['territorio_quilombola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_imovel_ti',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=True),
    sa.Column('terra_indigena_id', sa.UUID(), nullable=True),
    sa.Column('area_intersecao_ha', sa.Numeric(), nullable=True),
    sa.Column('percentual_sobreposicao', sa.Numeric(), nullable=True),
    sa.Column('tipo_relacao', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.ForeignKeyConstraint(['terra_indigena_id'], ['terra_indigena.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_imovel_uc',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('imovel_rural_id', sa.UUID(), nullable=True),
    sa.Column('unidade_conservacao_id', sa.UUID(), nullable=True),
    sa.Column('area_intersecao_ha', sa.Numeric(), nullable=True),
    sa.Column('percentual_sobreposicao', sa.Numeric(), nullable=True),
    sa.Column('tipo_relacao', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_rural_id'], ['imovel_rural.id'], ),
    sa.ForeignKeyConstraint(['unidade_conservacao_id'], ['unidade_conservacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'dataset', 'fonte_dado', ['fonte_dado_id'], ['id'])
    op.alter_column('fonte_dado', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'processamento', 'dataset', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processamento', type_='foreignkey')
    op.alter_column('fonte_dado', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_table('rel_imovel_uc')
    op.drop_table('rel_imovel_ti')
    op.drop_table('rel_imovel_quilombo')
    op.drop_table('rel_imovel_queimada')
    op.drop_table('rel_imovel_desmatamento')
    op.drop_table('rel_imovel_bacia')
    op.drop_table('rel_imovel_assentamento')
    op.drop_index(op.f('ix_feedback_resposta_resposta_sistema_id'), table_name='feedback_resposta')
    op.drop_table('feedback_resposta')
    op.drop_table('documento_trecho')
    op.drop_table('unidade_conservacao')
    op.drop_table('territorio_quilombola')
    op.drop_table('terra_indigena')
    op.drop_table('resposta_sistema')
    op.drop_table('queimada_evento')
    op.drop_table('imovel_rural')
    op.drop_table('documento')
    op.drop_table('desmatamento_alerta')
    op.drop_table('camada_estadual_ambiental')
    op.drop_table('assentamento_rural')
    op.drop_table('municipio')
    op.drop_table('consulta_usuario')
    op.drop_table('conceito_alias')
    op.drop_table('intencao_consulta')
    op.drop_table('grade_espacial')
    op.drop_table('estado')
    op.drop_table('conceito')
    op.drop_table('chat')
    op.drop_table('bacia_hidrografica')
    # ### end Alembic commands ###