"""empty message

Revision ID: a411c3dacc50
Revises: 
Create Date: 2026-04-01 13:47:39.191911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a411c3dacc50'
down_revision: Union[str, Sequence[str], None] = 'f178f7edc252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documento_trecho', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documento_trecho', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###