"""add geom column to rel_imovel_queimada

Revision ID: e45e0394d609
Revises: c4d5e6f7a8b9
Create Date: 2026-04-26 15:27:27.955236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e45e0394d609'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rel_imovel_queimada', sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rel_imovel_queimada', 'geom')
    # ### end Alembic commands ###