# -*- coding: utf-8 -*-
from __future__ import annotations

EXEMPLOS: list[tuple[str, str]] = [
    ("focos de queimada em Campinas", "queimada/listar"),
    ("incêndios em São Paulo", "queimada/listar"),
    ("queimadas detectadas em 2023", "queimada/listar"),
    ("foco de calor registrado no Cerrado", "queimada/listar"),
    ("onde houve fogo em São Paulo", "queimada/listar"),
    ("histórico de incêndios na região", "queimada/listar"),
    ("qual município tem mais queimadas", "queimada/rankear"),
    ("ranking de focos de incêndio por cidade", "queimada/rankear"),
    ("cidades com mais focos de calor em SP", "queimada/rankear"),
    ("top municípios com incêndios florestais", "queimada/rankear"),
    ("alertas de desmatamento em Marília", "desmatamento/listar"),
    ("supressão de vegetação em 2024", "desmatamento/listar"),
    ("corte raso detectado pelo PRODES", "desmatamento/listar"),
    ("alertas DETER de desmatamento", "desmatamento/listar"),
    ("perda de cobertura vegetal em Sorocaba", "desmatamento/listar"),
    ("municípios com mais desmatamento", "desmatamento/rankear"),
    ("ranking de supressão vegetal em SP", "desmatamento/rankear"),
    ("cidades com maior área desmatada", "desmatamento/rankear"),
    ("terras indígenas em Bauru", "terra_indigena/listar"),
    ("áreas de demarcação indígena no estado", "terra_indigena/listar"),
    ("reservas indígenas homologadas em SP", "terra_indigena/listar"),
    ("TI demarcada na região de Campinas", "terra_indigena/listar"),
    ("unidades de conservação em Sorocaba", "unidade_conservacao/listar"),
    ("parques nacionais e estaduais em SP", "unidade_conservacao/listar"),
    ("área de proteção ambiental na região", "unidade_conservacao/listar"),
    ("reserva extrativista no estado", "unidade_conservacao/listar"),
    ("APA federal no Vale do Paraíba", "unidade_conservacao/listar"),
    ("territórios quilombolas em Iguape", "quilombola/listar"),
    ("comunidades quilombolas no Vale do Ribeira", "quilombola/listar"),
    ("quilombos reconhecidos em São Paulo", "quilombola/listar"),
    ("assentamentos rurais do INCRA em Presidente Prudente", "assentamento/listar"),
    ("projetos de reforma agrária no estado", "assentamento/listar"),
    ("assentamentos do ITESP em São Paulo", "assentamento/listar"),
    ("imóveis rurais em Ribeirão Preto", "imovel_rural/listar"),
    ("fazenda cadastrada no CAR em Araçatuba", "imovel_rural/listar"),
    ("propriedades rurais com código CAR", "imovel_rural/listar"),
    ("passivos ambientais do imóvel SP-1234567-XXXXXXXX", "imovel_rural/passivos"),
    ("irregularidades ambientais na fazenda", "imovel_rural/passivos"),
    ("sobreposição da propriedade com áreas protegidas", "imovel_rural/passivos"),
    ("legislação ambiental sobre desmatamento", "documento/listar"),
    ("como funciona o licenciamento ambiental", "documento/listar"),
    ("o que diz o Código Florestal sobre APP", "documento/listar"),
    ("normativa CONAMA sobre queimadas", "documento/listar"),
    ("queimadas dentro de terras indígenas em SP", "queimada/listar"),
    ("focos de calor que intersectam reservas indígenas", "queimada/listar"),
    ("desmatamento dentro de unidades de conservação", "desmatamento/listar"),
    ("alertas de desmatamento em parques e reservas", "desmatamento/listar"),
    ("queimadas em territórios quilombolas", "queimada/listar"),
    ("incêndios dentro de assentamentos rurais", "queimada/listar"),
]
